org: numerouno51
app: stream-api
service: Stream-api-Hello-World

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

functions:
  hello:
    handler: handler.hello
    events: 
      - http: 
          path: /helloAWS
          method: get
